#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/scripts/startup.sh &
$HOME/.config/polybar/launch.sh
#wmname LG3D &
#backlight_control 25 &
/usr/bin/dunst &
pgrep -f bitwarden > /dev/null || bitwarden-desktop &
pgrep -x opensnitch-ui > /dev/null || opensnitch-ui &
#eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh) export SSH_AUTH_SOCK

# Test.

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	1
bspc config active_border_color         '#0C1115'
bspc config normal_border_color         '#0C1115'
bspc config focused_border_color        '#FF9D48'
bspc config window_gap          	12
bspc config top_padding 		22
bspc config bottom_padding		5
bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config click_to_focus	 	true
bspc config focus_follows_pointer 	true
bspc config ignore_ewmh_focus		true

bspc config -m HDMI-A-0 top_padding 5
# Rules for layout

# bspc wm -l $HOME/.config/bspwm/layout.layout
# sh $HOME/.config/bspwm/layout.rules
# sh $HOME/.config/bspwm/layout.init
