#!/bin/bash

# Startup actions
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/scripts/startup.sh &
#wmname LG3D &                    # For Java-based application e.g. Intellij

# To unlock keyring without DM
#eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh) export SSH_AUTH_SOCK

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	1
bspc config active_border_color         '#0C1115'
bspc config normal_border_color         '#0C1115'
bspc config focused_border_color        '#FF9D48'
bspc config window_gap          	12
bspc config top_padding 		22
bspc config bottom_padding		5
bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config click_to_focus	 	true
bspc config focus_follows_pointer 	true
bspc config ignore_ewmh_focus		true

# Rule for padding using internal monitor as primary to exclude polybar padding
# bspc config -m HDMI-A-0 top_padding 5
